apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kube-deployment
  labels:
    app: hello-kube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-kube
  template:
    metadata:
      labels:
        app: hello-kube
    spec:
      containers:
        - name: hello-kube
          image: jtlwheeler/hellokube
          imagePullPolicy: Never
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: hello-kube-service
spec:
  type: NodePort
  selector:
    app: hello-kube
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
